"Name: \FU:BAPI_ACC_INVOICE_RECEIPT_POST\SE:BEGIN\EI
ENHANCEMENT 0 Z_ADD_PAYMENT_METHOD1.
*
  DATA: LV_ZWELS     TYPE LFB1-ZWELS,  "Payment Method
      LS_ACCT      TYPE BAPIACAP03.
BREAK MOKHAN.
LOOP AT ACCOUNTPAYABLE INTO LS_ACCT.
   SELECT SINGLE ZWELS INTO LV_ZWELS FROM LFB1
    WHERE LIFNR = LS_ACCT-VENDOR_NO
      AND BUKRS = DOCUMENTHEADER-COMP_CODE.
   IF SY-SUBRC = 0.
      LS_ACCT-PYMT_METH = LV_ZWELS.
      MODIFY ACCOUNTPAYABLE FROM LS_ACCT TRANSPORTING PYMT_METH.
   ENDIF.
ENDLOOP.
ENDENHANCEMENT.
