REPORT ZFGLR001  NO STANDARD PAGE HEADING LINE-SIZE 110.
************************************************************************
*   Program    :  ZFGLR001
*   Programmer :  Gus Spartalis
*   Client     :  Centra-Union
*   Date       :  May 27th 1996
*
*THIS REPORT WILL DISPLAY THE ONTARIO CAPITAL TAX TOTALS FROM A RANGE
*OF ACCOUNTS UNDER THEIR GROUP HEADINGS.  THE REPORT WILL SHOW A LIST OF
*TWO COMPARATIVE DATES SPECIFIED BY THE USER.
*
* modified by Nancy Gilligan, OmniLogic D30K906105      "ngilligan 98/10
*   made constant rate a parameter, selected title to print based on
*   name of company, standardized headings, set company code default
*   based on client.
*
*CHANGES:
* 2005/08/24 mkhan TR105 Select Actual amount only as PLAN amount is   *
*                        going to be introduces in FI.                 *
************************************************************************

TABLES : GLT0,
         T001.           "company codes                  ngilligan 98/10
DATA   : R_TOTAL         TYPE  P DECIMALS 2,
         C_TOTAL             LIKE R_TOTAL,
         CAPITALSUB_R        LIKE R_TOTAL,
         CAPITALSUB_C        LIKE R_TOTAL,
         BOOKVALUESUB_R      LIKE R_TOTAL,
         BOOKVALUESUB_C      LIKE R_TOTAL,
         TAXVALUESUB_R       LIKE R_TOTAL,
         TAXVALUESUB_C       LIKE R_TOTAL,
         CAPTAXBEFINV_R      LIKE R_TOTAL,
         CAPTAXBEFINV_C      LIKE R_TOTAL,
         INVALLSUB_R         LIKE R_TOTAL,
         INVALLSUB_C         LIKE R_TOTAL,
         AMTDUCTACCESS_R     LIKE R_TOTAL,
         AMTDUCTACCESS_C     LIKE R_TOTAL,
         TOTALASSETS_R       LIKE R_TOTAL,
         TOTALASSETS_C       LIKE R_TOTAL,
         SECINVALLSUB_R      LIKE R_TOTAL,
         SECINVALLSUB_C      LIKE R_TOTAL,
         TAXCAP_R            LIKE R_TOTAL,
         TAXCAP_C            LIKE R_TOTAL,
         ONTARIOTAX_R        LIKE R_TOTAL,
         ONTARIOTAX_C        LIKE R_TOTAL,
         R_GRAND        TYPE P DECIMALS 2,
         C_GRAND            LIKE R_GRAND,
         TEST            TYPE I.
*onstants rate            type p decimals 2 value '0.03'.

SELECTION-SCREEN BEGIN OF LINE.
   SELECTION-SCREEN COMMENT 1(33) TEXT-200.
   PARAMETERS: PERIOD1(2)  TYPE N DEFAULT SY-DATUM+4(2),
               YEAR1(4)   DEFAULT SY-DATUM(4).
   SELECTION-SCREEN COMMENT 43(35)  TEXT-202.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
   SELECTION-SCREEN COMMENT 1(33) TEXT-201.
   PARAMETERS: PERIOD2(2) TYPE N DEFAULT 12, YEAR2(4).
   SELECTION-SCREEN COMMENT 43(35)  TEXT-203.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
   SELECTION-SCREEN COMMENT 1(33)  TEXT-205.
        PARAMETERS: P_CMCODE(4).
SELECTION-SCREEN END OF LINE.

PARAMETERS: P_RATE TYPE P DECIMALS 2 DEFAULT '0.03'.    "ngilligan 98/10
SELECTION-SCREEN SKIP.

************************************************************************
******************** FIRST SELECTION SCREEN BLOCK **********************
************************************************************************
SELECTION-SCREEN BEGIN OF BLOCK TAXCAP
                                WITH FRAME TITLE TEXT-213.
SELECT-OPTIONS:
     S_CAPSTK   FOR   GLT0-RACCT,   "CAPITAL STOCK
     S_RETNER   FOR   GLT0-RACCT,   "RETSINED EARNINGS
     S_OTHRLB   FOR   GLT0-RACCT,   "OTHER LIABILITIES
     S_CSTDPT   FOR   GLT0-RACCT,   "CUSTOMER DEPOSITS
     S_UCLMCQ   FOR   GLT0-RACCT,   "UNCLAIMED CHEQUES
     S_DINCLT   FOR   GLT0-RACCT,   "DEFERRED INCOME TAXES LONG TERM
     S_DINCCR   FOR   GLT0-RACCT,   "DEFERRED INCOME TAXES CURRENT
     S_LGTRMD   FOR   GLT0-RACCT,   "LONG TERM DEBT
     S_CRLGTD   FOR   GLT0-RACCT,   "CURRENT PORTION LONG TERM DEBT
     S_BKINDB   FOR   GLT0-RACCT.   "BANK INDEBTEDNESS

SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF BLOCK TAXCAPINPUT
                                WITH FRAME
                                TITLE TEXT-204.

        PARAMETERS: P_OUTSCQ    TYPE  P DECIMALS 2.
        PARAMETERS: C_OUTSCQ    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK TAXCAPINPUT.
SELECTION-SCREEN END OF BLOCK TAXCAP.
SELECTION-SCREEN SKIP 2.

************************************************************************
******************* SECOND SELECTION SCREEN BLOCK **********************
************************************************************************
SELECTION-SCREEN COMMENT 1(30) TEXT-217.
SELECTION-SCREEN BEGIN OF BLOCK BOOKVALUES
                                WITH FRAME
                                TITLE TEXT-214.
SELECT-OPTIONS:
     S_NBFXAS   FOR   GLT0-RACCT,   "NET BOOK VALUE FIXED ASSETS
     S_DBISCT   FOR   GLT0-RACCT,   "UNAMORTIZED DEBT ISSUE COSTS
     S_DISCST   FOR   GLT0-RACCT,   "DEFERRED ISSUE COSTS PREFER. SHARED
     S_IMPLHD   FOR   GLT0-RACCT,   "IMPROVEMENTS TO LEASED PREMISES
     S_PENSON   FOR   GLT0-RACCT,   "DEFERRED PENSION
     S_SUNDRY   FOR   GLT0-RACCT,   "DEFERRED SUNDRY EXPENSE
     S_DISCDI   FOR   GLT0-RACCT.   "UNAMORTIZED DISCOUNT DEBT. ISSUE

********************** SECOND  **** SECOND BLOCK
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF BLOCK BOOKVALUESINPUT2
                                WITH FRAME
                                TITLE TEXT-215.
PARAMETERS: P_CPLCNB    TYPE  P DECIMALS 2.
PARAMETERS: C_CPLCNB    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK BOOKVALUESINPUT2.

********************** SECOND ****  THIRD BLOCK
SELECTION-SCREEN BEGIN OF BLOCK BOOKVALUESINPUT3
                                WITH FRAME
                                TITLE TEXT-216.
PARAMETERS: P_CPLCAD    TYPE  P DECIMALS 2.
PARAMETERS: C_CPLCAD    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK BOOKVALUESINPUT3.

********************** SECOND  ****  FOURTH BLOCK
SELECTION-SCREEN BEGIN OF BLOCK BOOKVALUESINPUT4
                                WITH FRAME
                                TITLE TEXT-218.  "COST OF LAND IN NBV
PARAMETERS: P_LNDNBV    TYPE  P DECIMALS 2.
PARAMETERS: C_LNDNBV    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK BOOKVALUESINPUT4.

********************** SECOND  **** FIFTH  BLOCK
SELECTION-SCREEN BEGIN OF BLOCK BOOKVALUESINPUT5
                                WITH FRAME
                                TITLE TEXT-219.  "INTEREST DUR CONSTRUCT
PARAMETERS: P_INTCON    TYPE  P DECIMALS 2.
PARAMETERS: C_INTCON    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK BOOKVALUESINPUT5.

********************* SECOND  **** SIXTH BLOCK
SELECTION-SCREEN BEGIN OF BLOCK BOOKVALUESINPUT6
                                WITH FRAME
                                TITLE TEXT-220. "DEF. RATES HEARING COST
PARAMETERS: P_HEARCT    TYPE  P DECIMALS 2.
PARAMETERS: C_HEARCT    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK BOOKVALUESINPUT6.

SELECTION-SCREEN END OF BLOCK BOOKVALUES.
SELECTION-SCREEN SKIP 2.

************************************************************************
******************** THIRD SELECTION SCREEN BLOCK **********************
************************************************************************
SELECTION-SCREEN BEGIN OF BLOCK TAXVALUES
                                WITH FRAME
                                TITLE TEXT-300.

******************** THIRD  ****  FIRST  BLOCK
SELECTION-SCREEN BEGIN OF BLOCK TAXVALUES1
                                WITH FRAME
                                TITLE TEXT-301. "TAX VALUE
PARAMETERS: P_TAXVAL    TYPE  P DECIMALS 2.
PARAMETERS: C_TAXVAL    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK TAXVALUES1.

******************** THIRD  ****  SECOND BLOCK
SELECTION-SCREEN BEGIN OF BLOCK TAXVALUES2
                                WITH FRAME
                                TITLE TEXT-302.     "VCC
PARAMETERS: P_VCCVCC    TYPE  P DECIMALS 2.
PARAMETERS: C_VCCVCC    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK TAXVALUES2.

******************** THIRD  ****  THRID  BLOCK
SELECTION-SCREEN BEGIN OF BLOCK TAXVALUES3
                                WITH FRAME
                                TITLE TEXT-303.     "CEC
PARAMETERS: P_CECCEC    TYPE  P DECIMALS 2.
PARAMETERS: C_CECCEC    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK TAXVALUES3.

******************** THIRD  ****  FOURTH BLOCK
SELECTION-SCREEN BEGIN OF BLOCK TAXVALUES4
                                WITH FRAME
                                TITLE TEXT-304.   "NOT AVAILABLE FOR USE
PARAMETERS: P_NOTAVA    TYPE  P DECIMALS 2.
PARAMETERS: C_NOTAVA    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK TAXVALUES4.

******************** THIRD  ****   FIFTH  BLOCK
SELECTION-SCREEN BEGIN OF BLOCK TAXVALUES5
                                WITH FRAME
                                TITLE TEXT-305.     "NON DEDUCTIBLE CEC
PARAMETERS: P_NONDED    TYPE  P DECIMALS 2.
PARAMETERS: C_NONDED    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK TAXVALUES5.

******************** THIRD  ****  SIXTH  BLOCK
SELECTION-SCREEN BEGIN OF BLOCK TAXVALUES6
                                WITH FRAME
                                TITLE TEXT-306.     "RESOURCE PROPERTIES
PARAMETERS: P_RESPRO    TYPE  P DECIMALS 2.
PARAMETERS: C_RESPRO    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK TAXVALUES6.

******************** THIRD  ****  SEVENTH BLOCK
SELECTION-SCREEN BEGIN OF BLOCK TAXVALUES7
                                WITH FRAME
                                TITLE TEXT-307.     "DEBT ISSUE COST
PARAMETERS: P_DBISST    TYPE  P DECIMALS 2.
PARAMETERS: C_DBISST    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK TAXVALUES7.

SELECTION-SCREEN END OF BLOCK TAXVALUES.
SELECTION-SCREEN SKIP 2.

************************************************************************
******************* FOURTH SELECTION SCREEN BLOCK **********************
************************************************************************
SELECTION-SCREEN BEGIN OF BLOCK INVESTMENT
                                WITH FRAME
                                TITLE TEXT-400.  "INVESTMENT ALLOWANCE
SELECT-OPTIONS:
     S_INVWES   FOR   GLT0-RACCT,   "INVESTMENT WESTCOAST
     S_EQPKMP   FOR   GLT0-RACCT.   "EQUITY PICKUP MECAP

********************* FOURTH  **** SECOND BLOCK
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF BLOCK INVESTMENT2
                                WITH FRAME
                                TITLE TEXT-401. "MORTGAGE RECEIVABLE
PARAMETERS: P_MORGRV    TYPE  P DECIMALS 2.
PARAMETERS: C_MORGRV    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK INVESTMENT2.

SELECTION-SCREEN END OF BLOCK INVESTMENT.
SELECTION-SCREEN SKIP 2.

************************************************************************
******************** FIFTH SELECTION SCREEN BLOCK **********************
************************************************************************
SELECTION-SCREEN BEGIN OF BLOCK TOTALASSETS
                                WITH FRAME
                                TITLE TEXT-500.  "TOTAL ASSETS
SELECT-OPTIONS:
     S_ACCHRG   FOR   GLT0-RACCT.   "LESS ACCRUED CHARGES
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF BLOCK TOTALASSETS1
                                WITH FRAME
                                TITLE TEXT-501."TOTAL ASSETS PER BALANCE
PARAMETERS: P_TTASST    TYPE  P DECIMALS 2.    "TOTAL ASSETS
PARAMETERS: C_TTASST    TYPE  P DECIMALS 2.
SELECTION-SCREEN END OF BLOCK TOTALASSETS1.
SELECTION-SCREEN END OF BLOCK TOTALASSETS.

************************** INITIALIZATION ******************************
INITIALIZATION.
YEAR2 = SY-DATUM(4).
YEAR2 = YEAR2 - 1.

IF SY-MANDT+2(1) = '1'.
   P_CMCODE = 'UEC'.
ELSEIF SY-MANDT+2(1) = '0'.
   P_CMCODE = 'UGL'.
ENDIF.
********************************* MAIN *********************************
TOP-OF-PAGE. "   WITH HEADINGS

  WRITE: /1 TEXT-RPT, SY-REPID INTENSIFIED ON,          "ngilligan 98/10
         42 T001-BUTXT INTENSIFIED ON,                  "ngilligan 98/10
         80 TEXT-DTE, SY-DATUM, TEXT-AMP, SY-UZEIT.     "ngilligan 98/10

  WRITE: /1 TEXT-CLT, SY-MANDT UNDER SY-REPID,          "ngilligan 98/10
                                        SY-SYSID.       "ngilligan 98/10
  WRITE: TEXT-507 UNDER T001-BUTXT.                     "ngilligan 98/10
  WRITE: TEXT-PGE UNDER TEXT-DTE, SY-PAGNO.             "ngilligan 98/10
       SKIP 1.
       ULINE.    "INTENSIFIED OFF.
       WRITE: /50 TEXT-ASO    INTENSIFIED OFF.
       WRITE: /24 TEXT-101 INTENSIFIED OFF, 39 PERIOD1, 41 '/',42 YEAR1.
       WRITE: 51 TEXT-AND INTENSIFIED OFF.
       WRITE: 59 TEXT-102 INTENSIFIED OFF,76 PERIOD2, 78 '/' , 79 YEAR2.
       ULINE.
*      WRITE: /9 '10', 19 '20', 29 '30', 39 '40', 49 '50', 59 '60'.
*      WRITE: 69 '70', 79 '80', 89 '90', 98 '100', 108 '110'.
*      WRITE: / '12345678901234567890123456789012345678901234567890'.
*      WRITE: 51 '12345678901234567890123456789012345678901234567890'.
*      WRITE: 101 '1234567890'.
       WRITE: /.
       WRITE: /.
       WRITE: /58 TEXT-207, 87 TEXT-208.
       ULINE: /57(29), 86(20).
       WRITE: /79 SY-VLINE.

START-OF-SELECTION.
************************************************************************
*********************** FIRST SECTION OF REPORT ************************
************************************************************************
* get name of company                                   "ngilligan 98/10
  SELECT SINGLE BUTXT FROM T001 INTO T001-BUTXT WHERE BUKRS = P_CMCODE.


WRITE: /2 TEXT-213 INTENSIFIED OFF.
WRITE: 79 SY-VLINE.
ULINE: /1(17).
WRITE: 79 SY-VLINE.
WRITE: /79 SY-VLINE.


**************************** Capital Stock *****************************
PERFORM REGULARSELECT TABLES S_CAPSTK
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_CAPSTK USING TEXT-001.
PERFORM CAPITALSUB USING R_TOTAL C_TOTAL.

************************** Retained Earnings ***************************
PERFORM REGULARSELECT TABLES S_RETNER
              USING P_CMCODE  YEAR1     PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_RETNER USING TEXT-002.
PERFORM CAPITALSUB USING R_TOTAL C_TOTAL.

****** Other Liablities + Customer Deposits + Unclaimed Cheques ********
PERFORM CLEARGRAND.
PERFORM REGULARSELECT TABLES S_OTHRLB
              USING P_CMCODE  YEAR1     PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINESUB TABLES S_OTHRLB USING TEXT-003.

*******   *******   *******   *******   *******   *******   *******
PERFORM REGULARSELECT TABLES S_CSTDPT
              USING P_CMCODE  YEAR1     PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINESUB TABLES S_CSTDPT USING TEXT-004.

*******   *******   *******   *******   *******   *******   *******
PERFORM REGULARSELECT TABLES S_UCLMCQ
              USING P_CMCODE  YEAR1     PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINESUB TABLES S_UCLMCQ USING TEXT-005.
PERFORM GROUPTOTALS USING TEST.
PERFORM CAPITALSUB USING R_GRAND C_GRAND.

************ Deferred Income Taxes -- Long Term + Current **************
PERFORM CLEARGRAND.
PERFORM REGULARSELECT TABLES S_DINCLT
              USING P_CMCODE  YEAR1     PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINESUB TABLES S_DINCLT USING TEXT-006.

*******   *******   *******   *******   *******   *******   *******
PERFORM REGULARSELECT TABLES S_DINCCR
              USING P_CMCODE  YEAR1     PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINESUB TABLES S_DINCCR USING TEXT-007.
PERFORM GROUPTOTALS USING TEST.
PERFORM CAPITALSUB USING R_GRAND C_GRAND.

********** Long Term Debt + Current Portion Long Term Debt *************
PERFORM CLEARGRAND.
PERFORM REGULARSELECT TABLES S_LGTRMD
              USING P_CMCODE  YEAR1     PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINESUB TABLES S_LGTRMD USING TEXT-008.

*******   *******   *******   *******   *******   *******   *******
PERFORM CLEARGRAND.
PERFORM REGULARSELECT TABLES S_CRLGTD
              USING P_CMCODE  YEAR1     PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINESUB TABLES S_CRLGTD USING TEXT-009.
PERFORM GROUPTOTALS USING TEST.
PERFORM CAPITALSUB USING R_GRAND C_GRAND.

**************** Bank Indebtedness + Outstanding Cheques ***************
PERFORM CLEARGRAND.
PERFORM REGULARSELECT TABLES S_BKINDB
              USING P_CMCODE  YEAR1     PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINESUB TABLES S_BKINDB USING TEXT-010.

*****  Outstanding Cheques parameter is added to Bank Indebtedness *****
IF P_OUTSCQ NE 0 OR C_OUTSCQ NE 0.
PERFORM INDENTPARAM USING TEXT-011 P_OUTSCQ C_OUTSCQ.
ENDIF.
PERFORM GROUPTOTALS USING TEST.
PERFORM CAPITALSUB USING R_GRAND C_GRAND.

********************** TAXABLE CAPITAL SUB-TOTAL ***********************
PERFORM SUBTOTALS USING TEXT-209 CAPITALSUB_R CAPITALSUB_C.
************************************************************************

************************************************************************
********************** SECOND SECTION OF REPORT ************************
************************************************************************
NEW-PAGE.
WRITE: /2(27) TEXT-217 INTENSIFIED OFF.
WRITE: 79 SY-VLINE.
WRITE: /79 SY-VLINE.
WRITE: /2 TEXT-214 INTENSIFIED OFF.
WRITE: 79 SY-VLINE.
ULINE: /1(13).
WRITE: 79 SY-VLINE.
WRITE: /79 SY-VLINE.

*********************** NET BOOK VALUE FIXED ASSETS ********************
PERFORM REGULARSELECT TABLES S_NBFXAS
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_NBFXAS USING TEXT-221.
PERFORM BOOKVALUESUB USING R_TOTAL C_TOTAL.

********************CAPITALIZED LEASE COSTS IN NBV ********************
IF P_CPLCNB NE 0 OR C_CPLCNB NE 0.
PERFORM REGULARPARAM USING TEXT-226 P_CPLCNB C_CPLCNB.
ENDIF.
PERFORM BOOKVALUESUB USING P_CPLCNB C_CPLCNB.

******************* CAPITALIZED LEASE COSTS IN ACC DEP *****************
IF P_CPLCAD NE 0 OR C_CPLCAD NE 0.
PERFORM REGULARPARAM USING TEXT-227 P_CPLCAD C_CPLCAD.
ENDIF.
PERFORM BOOKVALUESUB USING P_CPLCAD C_CPLCAD.

************************* COST OF LAND IN NBV **************************
IF P_LNDNBV NE 0 OR C_LNDNBV NE 0.
PERFORM REGULARPARAM USING TEXT-218 P_LNDNBV C_LNDNBV.
ENDIF.
PERFORM BOOKVALUESUB USING P_LNDNBV C_LNDNBV.

*************** INTEREST DURING CONSTRUCTION INCLU. LAND  **************
IF P_INTCON NE 0 OR C_INTCON NE 0.
PERFORM REGULARPARAM USING TEXT-228 P_INTCON C_INTCON.
ENDIF.
PERFORM BOOKVALUESUB USING P_INTCON C_INTCON.

********************** UNAMORTIZED DEBT ISSUE COSTS ********************
PERFORM REGULARSELECT TABLES S_DBISCT
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_DBISCT USING TEXT-017.
PERFORM BOOKVALUESUB USING R_TOTAL C_TOTAL.


************** DEFERRED ISSUE COSTS - PREFERENCE SHARES ****************
PERFORM REGULARSELECT TABLES S_DISCST
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_DISCST USING TEXT-016.
PERFORM BOOKVALUESUB USING R_TOTAL C_TOTAL.

********************* DEFFERED RATE HEARING COSTS  *********************
IF P_HEARCT NE 0 OR C_HEARCT NE 0.
PERFORM REGULARPARAM USING TEXT-220 P_HEARCT C_HEARCT.
ENDIF.
PERFORM BOOKVALUESUB USING P_HEARCT C_HEARCT.

******************** IMPROVEMENTS TO LEASED PREMISES *******************
PERFORM REGULARSELECT TABLES S_IMPLHD
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_IMPLHD USING TEXT-018.
PERFORM BOOKVALUESUB USING R_TOTAL C_TOTAL.

*************************** DEFERRED PENSION ***************************
PERFORM REGULARSELECT TABLES S_PENSON
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_PENSON USING TEXT-223.
PERFORM BOOKVALUESUB USING R_TOTAL C_TOTAL.

************************ DEFERRED SUNDRY EXPENSE ***********************
PERFORM REGULARSELECT TABLES S_SUNDRY
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_SUNDRY USING TEXT-019.
PERFORM BOOKVALUESUB USING R_TOTAL C_TOTAL.

****************** UNAMORTIZED DISCOUNT DEBT ISSUE *********************
PERFORM REGULARSELECT TABLES S_DISCDI
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_DISCDI USING TEXT-224.
PERFORM BOOKVALUESUB USING R_TOTAL C_TOTAL.

************************ BOOK VALUES SUB-TOTAL *************************
PERFORM SUBTOTALS USING TEXT-222 BOOKVALUESUB_R BOOKVALUESUB_C.
************************************************************************

************************************************************************
*********************** THIRD SECTION OF REPORT ************************
************************************************************************
NEW-PAGE.
WRITE: /79 SY-VLINE.
WRITE: /2 TEXT-300 INTENSIFIED OFF.
WRITE: 79 SY-VLINE.
ULINE: /1(12).
WRITE: 79 SY-VLINE.
WRITE: /79 SY-VLINE.

******************************  TAX VALUES  ****************************
IF P_TAXVAL NE 0 OR C_TAXVAL NE 0.
PERFORM REGULARPARAM USING TEXT-301 P_TAXVAL C_TAXVAL.
ENDIF.
PERFORM TAXVALUESUB USING P_TAXVAL C_TAXVAL.

******************************** VCC  **********************************
IF P_VCCVCC NE 0 OR C_VCCVCC NE 0.
PERFORM REGULARPARAM USING TEXT-302 P_VCCVCC C_VCCVCC.
ENDIF.
PERFORM TAXVALUESUB USING P_VCCVCC C_VCCVCC.

***************************** CECCEC  **********************************
IF P_CECCEC NE 0 OR C_CECCEC NE 0.
PERFORM REGULARPARAM USING TEXT-303 P_CECCEC C_CECCEC.
ENDIF.
PERFORM TAXVALUESUB USING P_CECCEC C_CECCEC.

************************* NOT AVAILABLE FOR USE ************************
IF P_NOTAVA NE 0 OR C_NOTAVA NE 0.
PERFORM REGULARPARAM USING TEXT-304 P_NOTAVA C_NOTAVA.
ENDIF.
PERFORM TAXVALUESUB USING P_NOTAVA C_NOTAVA.

************************* NON DEDUCTIBLE CEC ***************************
IF P_NONDED NE 0 OR C_NONDED NE 0.
PERFORM REGULARPARAM USING TEXT-305 P_NONDED C_NONDED.
ENDIF.
PERFORM TAXVALUESUB USING P_NONDED C_NONDED.

************************* RESOURCE PROPERTIES **************************
IF P_RESPRO NE 0 OR C_RESPRO NE 0.
PERFORM REGULARPARAM USING TEXT-306 P_RESPRO C_RESPRO.
ENDIF.
PERFORM TAXVALUESUB USING P_RESPRO C_RESPRO.

************************** DEBT ISSUE COSTS ****************************
IF P_DBISST NE 0 OR C_DBISST NE 0.
PERFORM REGULARPARAM USING TEXT-307 P_DBISST C_DBISST.
ENDIF.
PERFORM TAXVALUESUB USING P_DBISST C_DBISST.

************************* TAX VALUES SUB-TOTAL *************************
PERFORM SUBTOTALS USING TEXT-310 TAXVALUESUB_R TAXVALUESUB_C.
************************************************************************

****************** AMOUNT DEDUCTED IN EXCESS CALCULATION ***************
AMTDUCTACCESS_R = ( - ( BOOKVALUESUB_R ) + TAXVALUESUB_R ).
AMTDUCTACCESS_C = ( - ( BOOKVALUESUB_C ) + TAXVALUESUB_C ).
CAPTAXBEFINV_R  = CAPITALSUB_R - AMTDUCTACCESS_R.
CAPTAXBEFINV_C  = CAPITALSUB_C - AMTDUCTACCESS_C.
WRITE: /.
WRITE: /.
WRITE: /.
WRITE: /.
WRITE: /.
PERFORM SUBTOTALS USING TEXT-229 AMTDUCTACCESS_R AMTDUCTACCESS_C.
PERFORM SUBTOTALS USING TEXT-230 CAPTAXBEFINV_R
                                 CAPTAXBEFINV_C.

************************************************************************
********************** FOURTH SECTION OF REPORT ************************
************************************************************************
NEW-PAGE.
WRITE: /79 SY-VLINE.
WRITE: /2 TEXT-400 INTENSIFIED OFF.
WRITE: 79 SY-VLINE.
ULINE: /1(22).
WRITE: 79 SY-VLINE.
WRITE: /79 SY-VLINE.

************************* INVESTMENT WESTCOAST *************************
PERFORM REGULARSELECT TABLES S_INVWES
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_INVWES USING TEXT-231.
PERFORM INVALLSUB USING R_TOTAL C_TOTAL.

************************** EQUITY PICKUP MECAP *************************
PERFORM REGULARSELECT TABLES S_EQPKMP
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_EQPKMP USING TEXT-232.
PERFORM INVALLSUB USING R_TOTAL C_TOTAL.

************************** MORTAGE WESTCOAST  **************************
IF P_MORGRV NE 0 OR C_MORGRV NE 0.
PERFORM REGULARPARAM USING TEXT-233 P_MORGRV C_MORGRV.
ENDIF.
PERFORM INVALLSUB USING P_MORGRV C_MORGRV.

********************* INVESTMENT ALLOWANCE SUB-TOTAL *******************
PERFORM SUBTOTALS USING TEXT-402 INVALLSUB_R INVALLSUB_C.
************************************************************************

************************************************************************
*********************** FIFTH SECTION OF REPORT ************************
************************************************************************
WRITE: /79 SY-VLINE.
WRITE: /79 SY-VLINE.
WRITE: /79 SY-VLINE.
WRITE: /2 TEXT-500 INTENSIFIED OFF.
WRITE: 79 SY-VLINE.
ULINE: /1(14).
WRITE: 79 SY-VLINE.
WRITE: /79 SY-VLINE.

********************* TOTAL ASSETS per BALANCE SHEET *******************
IF P_TTASST NE 0 OR C_TTASST NE 0.
PERFORM REGULARPARAM USING TEXT-501 P_TTASST C_TTASST.
ENDIF.

********************* LESS AMOUNT DEDUCTED IN EXCESS *******************
IF P_MORGRV NE 0 OR C_MORGRV NE 0.
PERFORM REGULARPARAM USING TEXT-505 AMTDUCTACCESS_R AMTDUCTACCESS_C.
ENDIF.

************************** LESS ACCRUED CHARGES ************************
PERFORM REGULARSELECT TABLES S_ACCHRG
              USING P_CMCODE  YEAR1    PERIOD1
                    YEAR2     PERIOD2.
PERFORM WRITEROUTINE1 TABLES S_ACCHRG USING TEXT-508.

************************ SUBTOTAL FOR TOTAL ASSETS *********************
TOTALASSETS_R = ( P_TTASST - AMTDUCTACCESS_R - R_TOTAL ).
TOTALASSETS_C = ( C_TTASST - AMTDUCTACCESS_C - C_TOTAL ).

PERFORM SUBTOTALS USING TEXT-500 TOTALASSETS_R TOTALASSETS_C.
WRITE: /.
WRITE: /.
WRITE: /.
WRITE: /.
***************** SECOND SUBTOTAL INVESTMENT ALLOWANCE *****************
SECINVALLSUB_R = ( CAPTAXBEFINV_R / TOTALASSETS_R * INVALLSUB_R ).
SECINVALLSUB_C = ( CAPTAXBEFINV_C / TOTALASSETS_C * INVALLSUB_C ).

PERFORM SUBTOTALS USING TEXT-400 SECINVALLSUB_R SECINVALLSUB_C.

******************* SECOND SUBTOTAL TAXABLE CAPITAL ********************
TAXCAP_R = ( CAPTAXBEFINV_R - SECINVALLSUB_R ).
TAXCAP_C = ( CAPTAXBEFINV_C - SECINVALLSUB_C ).

PERFORM SUBTOTALS USING TEXT-213 TAXCAP_R TAXCAP_C.

************************************************************************
************************* ONTARIO CAPITAL TAX***************************
************************************************************************
ONTARIOTAX_R = TAXCAP_R * P_RATE.
ONTARIOTAX_C = TAXCAP_C * P_RATE.

PERFORM SUBTOTALS USING TEXT-507 ONTARIOTAX_R ONTARIOTAX_C.

*************************** SUB ROUTINES *******************************
** This subroutine clears the totals before each heading calculation. **
FORM CLEARTOTAL.
R_TOTAL = 0.
C_TOTAL = 0.
ENDFORM.

FORM CLEARGRAND.
   R_GRAND = 0.
   C_GRAND = 0.
   TEST = 0.
ENDFORM.

************* This subroutine calculates the total for the *************
**************** REPORTING PERIOD AND COMPARATIVE PERIOD ***************
FORM RGRANDTOT USING PERIOD
               CHANGING TOTAL.

CASE PERIOD.
WHEN '1'.
       TOTAL = TOTAL + GLT0-TSL01.
WHEN '2'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02.
WHEN '3'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03.
WHEN '4'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
       + GLT0-TSL04.
WHEN '5'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
       + GLT0-TSL04 + GLT0-TSL05.
WHEN '6'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
       + GLT0-TSL04 + GLT0-TSL05 + GLT0-TSL06.
WHEN '7'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
       + GLT0-TSL04 + GLT0-TSL05 + GLT0-TSL06 + GLT0-TSL07.
WHEN '8'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
       + GLT0-TSL04 + GLT0-TSL05 + GLT0-TSL06 + GLT0-TSL07 + GLT0-TSL08.
WHEN '9'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
     + GLT0-TSL04 + GLT0-TSL05 + GLT0-TSL06 + GLT0-TSL07 + GLT0-TSL08
     + GLT0-TSL09.
WHEN '10'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
     + GLT0-TSL04 + GLT0-TSL05 + GLT0-TSL06 + GLT0-TSL07 + GLT0-TSL08
     + GLT0-TSL09 + GLT0-TSL10.
WHEN '11'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
     + GLT0-TSL04 + GLT0-TSL05 + GLT0-TSL06 + GLT0-TSL07 + GLT0-TSL08
     + GLT0-TSL09 + GLT0-TSL10 + GLT0-TSL11.
WHEN '12'.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
     + GLT0-TSL04 + GLT0-TSL05 + GLT0-TSL06 + GLT0-TSL07 + GLT0-TSL08
     + GLT0-TSL09 + GLT0-TSL10 + GLT0-TSL11 + GLT0-TSL12.
WHEN OTHERS.
       TOTAL = TOTAL + GLT0-TSL01 + GLT0-TSL02 + GLT0-TSL03
     + GLT0-TSL04 + GLT0-TSL05 + GLT0-TSL06 + GLT0-TSL07 + GLT0-TSL08
     + GLT0-TSL09 + GLT0-TSL10 + GLT0-TSL11 + GLT0-TSL12.
ENDCASE.
ENDFORM.

******* This routine handles the subtotal for TAXABLE CAPITAL **********
FORM CAPITALSUB USING R_SUBTOTAL C_SUBTOTAL.
CAPITALSUB_R = CAPITALSUB_R + R_SUBTOTAL.
CAPITALSUB_C = CAPITALSUB_C + C_SUBTOTAL.
ENDFORM.

********** This routine handles the subtotal for BOOK VALUE ************
FORM BOOKVALUESUB USING R_SUBTOTAL C_SUBTOTAL.
BOOKVALUESUB_R = BOOKVALUESUB_R + R_SUBTOTAL.
BOOKVALUESUB_C = BOOKVALUESUB_C + C_SUBTOTAL.
ENDFORM.

********** This routine handles the subtotal for TAX VALUE *************
FORM TAXVALUESUB USING R_SUBTOTAL C_SUBTOTAL.
TAXVALUESUB_R = TAXVALUESUB_R + R_SUBTOTAL.
TAXVALUESUB_C = TAXVALUESUB_C + C_SUBTOTAL.
ENDFORM.

********** This routine handles the subtotal for TAX VALUE *************
FORM INVALLSUB USING R_SUBTOTAL C_SUBTOTAL.
INVALLSUB_R = INVALLSUB_R + R_SUBTOTAL.
INVALLSUB_C = INVALLSUB_C + C_SUBTOTAL.
ENDFORM.

************************** SECTION SUB-TOTAL ***************************
FORM SUBTOTALS USING SUBTOTALTEXT SUBTOTALS_R SUBTOTALS_C.
ULINE.
WRITE: /1 SUBTOTALTEXT, 59 TEXT-206, 61 SUBTOTALS_R.
WRITE: 94 TEXT-206, 96 SUBTOTALS_C.
ULINE.
ENDFORM.

***** This routine handles the printing of each line of the report *****
FORM WRITEROUTINE1 TABLES GUSTAB
                   STRUCTURE S_CAPSTK
                   USING TEXT.
SY-INDEX = 1.
LOOP AT GUSTAB.
IF SY-INDEX = 1.
    WRITE: / GUSTAB-LOW, 8 '-', 10 GUSTAB-HIGH, 18(27) TEXT.
    WRITE: 61 R_TOTAL EXPONENT 0 DECIMALS 2, 79 SY-VLINE.
    WRITE: 96 C_TOTAL DECIMALS 2.
    SY-INDEX = SY-INDEX + 1.
ELSE.
    WRITE: / GUSTAB-LOW, 8 '-', 10 GUSTAB-HIGH, 79 SY-VLINE.
    SY-INDEX = SY-INDEX + 1.
ENDIF.
ENDLOOP.
WRITE: /79 SY-VLINE.
ENDFORM.

***** This routine handles the printing of the indented subgroups ******
FORM WRITEROUTINESUB TABLES GUSTABSUB
                     STRUCTURE S_CAPSTK
                     USING SUBTEXT.
SY-INDEX = 1.
LOOP AT GUSTABSUB.
IF SY-INDEX = 1.
WRITE: / GUSTABSUB-LOW, 8 '-', 10 GUSTABSUB-HIGH, 18(27) SUBTEXT.
WRITE: 45 R_TOTAL EXPONENT 0 DECIMALS 2 INTENSIFIED OFF, 79 SY-VLINE.
WRITE: 80 C_TOTAL DECIMALS 2 INTENSIFIED OFF.
R_GRAND = R_GRAND + R_TOTAL.
C_GRAND = C_GRAND + C_TOTAL.
    SY-INDEX = SY-INDEX + 1.
ELSE.
    WRITE: / GUSTABSUB-LOW, 8 '-', 10 GUSTABSUB-HIGH, 79 SY-VLINE.
    SY-INDEX = SY-INDEX + 1.
ENDIF.
ENDLOOP.
ENDFORM.

****** This routine prints the totals for the indented subgroups *******
FORM GROUPTOTALS USING TEST.
IF TEST = 1.
WRITE: /47 TEXT-210, 61 R_GRAND DECIMALS 2, 79 SY-VLINE, 82 TEXT-210.
WRITE: 96 C_GRAND DECIMALS 2.
WRITE:/79 SY-VLINE.
WRITE:/79 SY-VLINE.
ENDIF.
ENDFORM.

******************** REGULAR SELECT ROUTINE ********************
FORM REGULARSELECT TABLES ACCOUNT
        STRUCTURE S_CAPSTK
           USING TESTP_CMCODE TESTYEAR1 TESTPERIOD1
                 TESTYEAR2 TESTPERIOD2.

PERFORM CLEARTOTAL.
SELECT * FROM GLT0 WHERE RRCTY = '0'              "Actual Amount TR105
                     AND RACCT IN ACCOUNT
                     AND BUKRS = TESTP_CMCODE
                     AND RYEAR = TESTYEAR1.
IF ACCOUNT-LOW NE 0.
PERFORM RGRANDTOT USING TESTPERIOD1 CHANGING R_TOTAL.
TEST = 1.
ENDIF.
ENDSELECT.

SELECT * FROM GLT0 WHERE RRCTY = '0'              "Actual Amount TR105
                     AND RACCT IN ACCOUNT
                     AND BUKRS = P_CMCODE
                     AND RYEAR = YEAR2.
IF ACCOUNT-LOW NE 0.
PERFORM RGRANDTOT USING TESTPERIOD2 CHANGING C_TOTAL.
ENDIF.
ENDSELECT.
ENDFORM.

*************** Print Paramaters NOT IN Indented Form ******************
FORM REGULARPARAM  USING TEXT PP_VAR CC_VAR.
    WRITE: /18(27) TEXT.
    WRITE: 61 PP_VAR DECIMALS 2, 79 SY-VLINE.
    WRITE: 96 CC_VAR DECIMALS 2.
WRITE: /79 SY-VLINE.
ENDFORM.

******************* Print Paramaters IN INDENTED FORM ******************
FORM INDENTPARAM USING TEXT P_VAR C_VAR.
WRITE: /18(27) TEXT, 45 P_VAR DECIMALS 2 INTENSIFIED OFF.
WRITE: 79 SY-VLINE,  80 C_VAR DECIMALS 2 INTENSIFIED OFF.
TEST = 1.

R_GRAND = R_GRAND + P_VAR.
C_GRAND = C_GRAND + C_VAR.
ENDFORM.
