*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZFIMV_FCALENDAR.................................*
FORM GET_DATA_ZFIMV_FCALENDAR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFIT_FCALENDAR WHERE
(VIM_WHERETAB) .
    CLEAR ZFIMV_FCALENDAR .
ZFIMV_FCALENDAR-MANDT =
ZFIT_FCALENDAR-MANDT .
ZFIMV_FCALENDAR-FCAL =
ZFIT_FCALENDAR-FCAL .
    SELECT SINGLE * FROM TFACD WHERE
IDENT = ZFIT_FCALENDAR-FCAL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TFACT WHERE
IDENT = TFACD-IDENT AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZFIMV_FCALENDAR-LTEXT =
TFACT-LTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZFIMV_FCALENDAR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZFIMV_FCALENDAR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZFIMV_FCALENDAR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZFIMV_FCALENDAR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFIT_FCALENDAR WHERE
  FCAL = ZFIMV_FCALENDAR-FCAL .
    IF SY-SUBRC = 0.
    DELETE ZFIT_FCALENDAR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFIT_FCALENDAR WHERE
  FCAL = ZFIMV_FCALENDAR-FCAL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFIT_FCALENDAR.
    ENDIF.
ZFIT_FCALENDAR-MANDT =
ZFIMV_FCALENDAR-MANDT .
ZFIT_FCALENDAR-FCAL =
ZFIMV_FCALENDAR-FCAL .
    IF SY-SUBRC = 0.
    UPDATE ZFIT_FCALENDAR .
    ELSE.
    INSERT ZFIT_FCALENDAR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZFIMV_FCALENDAR-UPD_FLAG,
STATUS_ZFIMV_FCALENDAR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZFIMV_FCALENDAR.
  SELECT SINGLE * FROM ZFIT_FCALENDAR WHERE
FCAL = ZFIMV_FCALENDAR-FCAL .
ZFIMV_FCALENDAR-MANDT =
ZFIT_FCALENDAR-MANDT .
ZFIMV_FCALENDAR-FCAL =
ZFIT_FCALENDAR-FCAL .
    SELECT SINGLE * FROM TFACD WHERE
IDENT = ZFIT_FCALENDAR-FCAL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TFACT WHERE
IDENT = TFACD-IDENT AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZFIMV_FCALENDAR-LTEXT =
TFACT-LTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZFIMV_FCALENDAR-LTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZFIMV_FCALENDAR-LTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZFIMV_FCALENDAR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZFIMV_FCALENDAR-FCAL TO
ZFIT_FCALENDAR-FCAL .
MOVE ZFIMV_FCALENDAR-MANDT TO
ZFIT_FCALENDAR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIT_FCALENDAR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIT_FCALENDAR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIT_FCALENDAR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZFIMV_FCALENDAR USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFIT_FCALENDAR-MANDT =
ZFIMV_FCALENDAR-MANDT .
ZFIT_FCALENDAR-FCAL =
ZFIMV_FCALENDAR-FCAL .
    SELECT SINGLE * FROM TFACD WHERE
IDENT = ZFIT_FCALENDAR-FCAL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TFACT WHERE
IDENT = TFACD-IDENT AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZFIMV_FCALENDAR-LTEXT =
TFACT-LTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZFIMV_FCALENDAR-LTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZFIMV_FCALENDAR-LTEXT .
    ENDIF.
ENDFORM.
