*&---------------------------------------------------------------------*
*&  Include           ZFI_US_READ_MD_FOR_IS_TOP
*&---------------------------------------------------------------------*
TABLES: DD02L, EQUZ, EQUI, EQKT, ILOA, EQST, JEST, AUSP, PROP, MARD, EINA,MBEW,
        ADR6, EKKO, LFM1, NAST, T024, EKPO,EKET,BKPF,BSEG,T001,TJ02T, BPJA, PRTE, EKBE,
        VBSEGK,BSIK,VBSEGD,BSID,COEJ,CSKS,EKKN,IHPA,KSSK,T006,T006A,T023T, PRPS,SOOD,SRGBTBREL,
        T399D,TCJ04,TJ03,TKT09,MSEG,AFIH,INOB,ITOB,STXL,STAS,QMFE,MAKT,TOA01,DRAD,DMS_DOC2LOIO,DMS_PH_CD1,DRAT.

CONSTANTS: HTAB     TYPE ABAP_CHAR1 VALUE CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB,
           NLINE TYPE ABAP_CHAR1 VALUE CL_ABAP_CHAR_UTILITIES=>NEWLINE,
           HCR_LF   TYPE ABAP_CR_LF VALUE CL_ABAP_CHAR_UTILITIES=>CR_LF.

DATA: GV_FIELDNAME TYPE FIELDNAME.

TYPES: BEGIN OF TY_KEYS,
        FIELDNAME TYPE FIELDNAME,
       END OF TY_KEYS,

       BEGIN OF TY_COND,
         COND(72) TYPE C,
       END OF TY_COND,

       TY_T_KEYS TYPE STANDARD TABLE OF TY_KEYS,
       TY_T_COND TYPE STANDARD TABLE OF TY_COND.

RANGES: R_KEYS FOR GV_FIELDNAME.

TYPES: BEGIN OF TY_AUSP,
         MATNR  TYPE MATNR,
         OBJEK  TYPE OBJNUM,
         ATINN  TYPE ATINN,
         ATZHL  TYPE WZAEHL,
         MAFID  TYPE KLMAF,
         KLART  TYPE KLASSENART,
         ADZHL  TYPE ADZHL,
         ATWRT  TYPE ATWRT,
         ATBEZ  TYPE ATBEZ, "Characteristic Name
       END OF TY_AUSP,

       BEGIN OF TY_MAT_CHARAC,
         MATNR  TYPE MATNR,
         ATBEZ  TYPE  ATBEZ, "Characteristic Name
         ATWRT  TYPE ATWRT,
       END OF TY_MAT_CHARAC,

       BEGIN OF TY_STXL,
          MANDT	   TYPE STXL-MANDT,
          RELID	   TYPE SYCHAR02,
          TDOBJECT TYPE TDOBJECT,
          TDNAME   TYPE TDOBNAME,
          TDID     TYPE TDID,
          TDSPRAS	 TYPE SPRAS,
          SRTF2	   TYPE SYBIN1,
          CLUSTR   TYPE SYBIN2,
       END OF TY_STXL.

TYPES : BEGIN OF TY_MARAAUSP.
        INCLUDE STRUCTURE MARA.
TYPES: ATBEZ  TYPE ATBEZ.
TYPES: ATWRT  TYPE ATWRT.
TYPES : END OF TY_MARAAUSP.

TYPES: BEGIN OF TY_TOA01,
        SAP_OBJECT TYPE SAEANWDID,
        OBJECT_ID	 TYPE SAEOBJID,
        ARCHIV_ID	 TYPE SAEARCHIVI,
        ARC_DOC_ID TYPE	SAEARDOID,
        AR_OBJECT	 TYPE SAEOBJART,
        AR_DATE	   TYPE SAEABADATE,
        DEL_DATE   TYPE SAEDELDATE,
        RESERVE	   TYPE SAERESERVE,
        ARC_DOC_ID2 TYPE  SAEARDOID,
        FILENAME   TYPE CHAR255,
        CREATOR	   TYPE SYUNAME,
        DESCR(60)  TYPE C,
        CREATIME   TYPE SYTIME,
      END OF TY_TOA01.

TYPES : BEGIN OF TY_DRAD.
        INCLUDE STRUCTURE DRAD.
TYPES: MANDT_2  TYPE MANDT,
      DOKAR_2    TYPE DOKAR,
DOKNR_2	TYPE DOKNR,
DOKVR_2	TYPE DOKVR,
DOKTL_2	TYPE DOKTL_D,
LO_TYPE	TYPE DMS_FILE_TYPE,
LO_INDEX  TYPE DMS_DOC_INDEX,
LO_OBJID  TYPE SDOK_LOID,
LO_IS_REF	TYPE CVFLAG,
MANDT_3	TYPE MANDT,
PHIO_ID	TYPE SDOK_PHID,
PH_CLASS  TYPE SDOK_PHCL,
LOIO_ID	TYPE SDOK_LOID,
LO_CLASS  TYPE SDOK_LOCL,
STATE	TYPE SDOK_PHSTA,
DESCRIPT  TYPE SDOK_TITEL,
LANGU	TYPE SPRAS,
CREA_USER	TYPE SDOK_CRUSR,
CREA_TIME	TYPE SDOK_CRTST,
CHNG_USER	TYPE SDOK_CHUSR,
CHNG_TIME	TYPE SDOK_CHTST,
STOR_CAT  TYPE SDOK_STCAT,
DOC_FORMAT  TYPE SDOK_FORM,
DOC_PROT  TYPE SDOK_DPROT,
PROP01  TYPE SDOK_PRV_S,
PROP02  TYPE SDOK_PRV_S,
PROP03  TYPE SDOK_PRV_S,
PROP04  TYPE SDOK_PRV_S,
PROP05  TYPE SDOK_PRV_M,
PROP06  TYPE SDOK_PRV_M,
PROP07  TYPE SDOK_PRV_M,
PROP08  TYPE SDOK_PRV_L,
PROP09  TYPE SDOK_PRV_L,
PROP10  TYPE SDOK_PRV_L,
MANDT_4 TYPE  MANDT,
DOKAR_4   TYPE  DOKAR,
DOKNR_4  TYPE  DOKNR,
DOKVR_4  TYPE  DOKVR,
DOKTL_4   TYPE  DOKTL_D,
LANGU_4   TYPE  CVLANG,
DKTXT   TYPE  DKTXT,
LTXIN   TYPE  LTXIN,
DKTXT_UC TYPE	DKTXT_UC.
TYPES : END OF TY_DRAD,

  BEGIN OF TY_SOODK,
              RELTYPE   TYPE OBLRELTYPE,
              INSTID_A  TYPE SIBFBORIID,
              TYPEID_A   TYPE SIBFTYPEID,
              TYPEID_B   TYPE SIBFTYPEID,
              OBJTP TYPE  SO_OBJ_TP,
              OBJYR	TYPE  SO_OBJ_YR,
              OBJNO TYPE  SO_OBJ_NO,
              OBJDES TYPE SO_OBJ_DES,
              TEXTS TYPE  SO_TEXT255,
           END OF TY_SOODK.


TYPES: BEGIN OF TY_SRGBTBREL,
         EMAIL TYPE SOLIX,
       END OF TY_SRGBTBREL.

TYPES: TY_T_MAT_CHARAC TYPE STANDARD TABLE OF TY_MAT_CHARAC,
       TY_T_MARA_AUSP   TYPE STANDARD TABLE OF TY_MARAAUSP.

*TYPES: BEGIN OF ty_stxl.
*        INCLUDE STRUCTURE stxl.
**TYPES: TEXT TYPE STRING.
*TYPES: END OF ty_stxl.

DATA: GV_LIFNR TYPE LFA1-LIFNR,
      GV_BUKRS TYPE LFB1-BUKRS,
      GV_PSPNR TYPE PROJ-PSPNR,
      GV_PRPS  TYPE PRPS-PSPNR,
      GV_AUFNR TYPE AUFK-AUFNR,
      GV_WERKS TYPE T499S-WERKS,
      GV_STAND TYPE T499S-STAND,
      GV_TPLNR TYPE IFLOT-TPLNR,
      GV_ANLN1 TYPE ANLA-ANLN1,
      GV_ANLN2 TYPE ANLA-ANLN2,
      GV_BANKS TYPE BNKA-BANKS,
      GV_BANKL TYPE BNKA-BANKL,
      GV_HBKID TYPE T012-HBKID,
      GV_HKTID TYPE T012K-HKTID,
      GV_KUNNR TYPE KNA1-KUNNR,
      GV_LGORT TYPE T001L-LGORT,
      GV_MATNR TYPE MARA-MATNR,
      GV_EQUNR TYPE EQUI-EQUNR,
      GV_FLAG  TYPE C.

DATA: GT_LFA1  TYPE STANDARD TABLE OF LFA1,
      GT_LFB1  TYPE STANDARD TABLE OF LFB1,
      GT_PRPS  TYPE STANDARD TABLE OF PRPS,
      GT_AUFK  TYPE STANDARD TABLE OF AUFK,
      GT_PROJ  TYPE STANDARD TABLE OF PROJ,
      GT_T499S TYPE STANDARD TABLE OF T499S,
      GT_IFLOT TYPE STANDARD TABLE OF IFLOT,
      GT_ANLA  TYPE STANDARD TABLE OF ANLA,
      GT_BNKA  TYPE STANDARD TABLE OF BNKA,
      GT_T012  TYPE STANDARD TABLE OF T012,
      GT_T012K TYPE STANDARD TABLE OF T012K,
      GT_ANLH  TYPE STANDARD TABLE OF ANLH,
      GT_KNA1  TYPE STANDARD TABLE OF KNA1,
      GT_KNB1  TYPE STANDARD TABLE OF KNB1,
      GT_MARA  TYPE STANDARD TABLE OF MARA,
      GT_MARC  TYPE STANDARD TABLE OF  MARC,
      GT_T001L TYPE STANDARD TABLE OF T001L,
      GT_EQUI  TYPE STANDARD TABLE OF EQUI,
      GT_T001W TYPE STANDARD TABLE OF T001W,
      GT_AUSP  TYPE STANDARD TABLE OF TY_AUSP,
      GT_TOA01 TYPE STANDARD TABLE OF TY_TOA01,
      GT_DRAD  TYPE STANDARD TABLE OF TY_DRAD,
      GT_MAT_CHARAC TYPE STANDARD TABLE OF TY_MAT_CHARAC,
      GT_MARA_AUSP  TYPE TY_T_MARA_AUSP,
      GT_ADR6       TYPE STANDARD TABLE OF ADR6,
      gt_ekbe type STANDARD TABLE OF ekbe,
      GT_IHPA       TYPE STANDARD TABLE OF IHPA,
      GT_STXL       TYPE STANDARD TABLE OF TY_STXL,
      GT_SOODK       TYPE STANDARD TABLE OF TY_SOODK,
      GT_KEYS  TYPE TY_T_KEYS,
      GT_DFIES TYPE STANDARD TABLE OF DFIES,
      GV_PKG_SIZE TYPE I,
      GV_STRUC_SIZE TYPE I,
      GT_COND   TYPE TY_T_COND,
      GV_COUNT  TYPE SYDBCNT,
      GV_COUNT2 TYPE SYDBCNT,
      GV_FILE_NO(4) TYPE N,
      GV_LINES TYPE I,
      GT_LIST   TYPE VRM_VALUES,
      GV_INSTID_A  TYPE SIBFBORIID,
      GV_BRELGUID  TYPE STRING.

FIELD-SYMBOLS : <GT_DATA> TYPE ANY TABLE.

DATA: GR_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GS_LAYOUT    TYPE SLIS_LAYOUT_ALV,
      OK_CODE      TYPE SY-UCOMM.
