FUNCTION Z_POPUP_WITH_2_OPTIONS.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(DEFAULTOPTION) TYPE  C DEFAULT '1'
*"     VALUE(TEXTLINE1) TYPE  C
*"     VALUE(TEXTLINE2) TYPE  C DEFAULT SPACE
*"     VALUE(TEXTLINE3) TYPE  C DEFAULT SPACE
*"     VALUE(TEXTLINE4) TYPE  C DEFAULT SPACE
*"     VALUE(TEXTLINE5) TYPE  C DEFAULT SPACE
*"     VALUE(TEXT_OPTION1) TYPE  C
*"     VALUE(TEXT_OPTION2) TYPE  C OPTIONAL
*"     VALUE(TITLE) TYPE  C
*"     VALUE(START_COLUMN) LIKE  SY-CUCOL DEFAULT 25
*"     VALUE(START_ROW) LIKE  SY-CUROW DEFAULT 6
*"  EXPORTING
*"     VALUE(ANSWER) TYPE  XFELD
*"----------------------------------------------------------------------

  POPUP-TITLE = TITLE.
  POPUP-TEXTLINE1 = TEXTLINE1.
  POPUP-TEXTLINE2 = TEXTLINE2.
  POPUP-TEXTLINE3 = TEXTLINE3.
  POPUP-TEXTLINE4 = TEXTLINE4.
  POPUP-TEXTLINE5 = TEXTLINE5.
  POPUP-OPTION1 = TEXT_OPTION1.
  POPUP-OPTION2 = TEXT_OPTION2.
  CASE DEFAULTOPTION.
    WHEN '1'.
      OPTION = '1'.
    WHEN '2'.
      OPTION = '2'.
  ENDCASE.

  CALL SCREEN 300 STARTING AT START_COLUMN START_ROW.
  ANSWER = ANTWORT.




ENDFUNCTION.
