*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZFIMV_DOA.......................................*
FORM GET_DATA_ZFIMV_DOA.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFIT_DOA WHERE
(VIM_WHERETAB) .
    CLEAR ZFIMV_DOA .
ZFIMV_DOA-MANDT =
ZFIT_DOA-MANDT .
ZFIMV_DOA-LOOKUP_KEY =
ZFIT_DOA-LOOKUP_KEY .
ZFIMV_DOA-LOOKUP_KEY_TYPE =
ZFIT_DOA-LOOKUP_KEY_TYPE .
ZFIMV_DOA-TCODE =
ZFIT_DOA-TCODE .
ZFIMV_DOA-DOC_TYPE =
ZFIT_DOA-DOC_TYPE .
ZFIMV_DOA-AMOUNT =
ZFIT_DOA-AMOUNT .
ZFIMV_DOA-VORNA =
ZFIT_DOA-VORNA .
ZFIMV_DOA-NACHN =
ZFIT_DOA-NACHN .
ZFIMV_DOA-CHANGEDBY =
ZFIT_DOA-CHANGEDBY .
ZFIMV_DOA-CHANGEDON =
ZFIT_DOA-CHANGEDON .
    SELECT SINGLE * FROM T000.
    IF SY-SUBRC EQ 0.
    ENDIF.
    SELECT SINGLE * FROM TSTC WHERE
TCODE = ZFIT_DOA-TCODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TSTCT WHERE
TCODE = TSTC-TCODE AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZFIMV_DOA-TTEXT =
TSTCT-TTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZFIMV_DOA.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZFIMV_DOA .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZFIMV_DOA.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZFIMV_DOA-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFIT_DOA WHERE
  LOOKUP_KEY = ZFIMV_DOA-LOOKUP_KEY AND
  LOOKUP_KEY_TYPE = ZFIMV_DOA-LOOKUP_KEY_TYPE AND
  TCODE = ZFIMV_DOA-TCODE AND
  DOC_TYPE = ZFIMV_DOA-DOC_TYPE .
    IF SY-SUBRC = 0.
    DELETE ZFIT_DOA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFIT_DOA WHERE
  LOOKUP_KEY = ZFIMV_DOA-LOOKUP_KEY AND
  LOOKUP_KEY_TYPE = ZFIMV_DOA-LOOKUP_KEY_TYPE AND
  TCODE = ZFIMV_DOA-TCODE AND
  DOC_TYPE = ZFIMV_DOA-DOC_TYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFIT_DOA.
    ENDIF.
ZFIT_DOA-MANDT =
ZFIMV_DOA-MANDT .
ZFIT_DOA-LOOKUP_KEY =
ZFIMV_DOA-LOOKUP_KEY .
ZFIT_DOA-LOOKUP_KEY_TYPE =
ZFIMV_DOA-LOOKUP_KEY_TYPE .
ZFIT_DOA-TCODE =
ZFIMV_DOA-TCODE .
ZFIT_DOA-DOC_TYPE =
ZFIMV_DOA-DOC_TYPE .
ZFIT_DOA-AMOUNT =
ZFIMV_DOA-AMOUNT .
ZFIT_DOA-VORNA =
ZFIMV_DOA-VORNA .
ZFIT_DOA-NACHN =
ZFIMV_DOA-NACHN .
ZFIT_DOA-CHANGEDBY =
ZFIMV_DOA-CHANGEDBY .
ZFIT_DOA-CHANGEDON =
ZFIMV_DOA-CHANGEDON .
    IF SY-SUBRC = 0.
    UPDATE ZFIT_DOA .
    ELSE.
    INSERT ZFIT_DOA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZFIMV_DOA-UPD_FLAG,
STATUS_ZFIMV_DOA-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZFIMV_DOA.
  SELECT SINGLE * FROM ZFIT_DOA WHERE
LOOKUP_KEY = ZFIMV_DOA-LOOKUP_KEY AND
LOOKUP_KEY_TYPE = ZFIMV_DOA-LOOKUP_KEY_TYPE AND
TCODE = ZFIMV_DOA-TCODE AND
DOC_TYPE = ZFIMV_DOA-DOC_TYPE .
ZFIMV_DOA-MANDT =
ZFIT_DOA-MANDT .
ZFIMV_DOA-LOOKUP_KEY =
ZFIT_DOA-LOOKUP_KEY .
ZFIMV_DOA-LOOKUP_KEY_TYPE =
ZFIT_DOA-LOOKUP_KEY_TYPE .
ZFIMV_DOA-TCODE =
ZFIT_DOA-TCODE .
ZFIMV_DOA-DOC_TYPE =
ZFIT_DOA-DOC_TYPE .
ZFIMV_DOA-AMOUNT =
ZFIT_DOA-AMOUNT .
ZFIMV_DOA-VORNA =
ZFIT_DOA-VORNA .
ZFIMV_DOA-NACHN =
ZFIT_DOA-NACHN .
ZFIMV_DOA-CHANGEDBY =
ZFIT_DOA-CHANGEDBY .
ZFIMV_DOA-CHANGEDON =
ZFIT_DOA-CHANGEDON .
    SELECT SINGLE * FROM T000.
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM TSTC WHERE
TCODE = ZFIT_DOA-TCODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TSTCT WHERE
TCODE = TSTC-TCODE AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZFIMV_DOA-TTEXT =
TSTCT-TTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZFIMV_DOA-TTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZFIMV_DOA-TTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZFIMV_DOA USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZFIMV_DOA-LOOKUP_KEY TO
ZFIT_DOA-LOOKUP_KEY .
MOVE ZFIMV_DOA-LOOKUP_KEY_TYPE TO
ZFIT_DOA-LOOKUP_KEY_TYPE .
MOVE ZFIMV_DOA-TCODE TO
ZFIT_DOA-TCODE .
MOVE ZFIMV_DOA-DOC_TYPE TO
ZFIT_DOA-DOC_TYPE .
MOVE ZFIMV_DOA-MANDT TO
ZFIT_DOA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIT_DOA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIT_DOA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIT_DOA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZFIMV_DOA USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFIT_DOA-MANDT =
ZFIMV_DOA-MANDT .
ZFIT_DOA-LOOKUP_KEY =
ZFIMV_DOA-LOOKUP_KEY .
ZFIT_DOA-LOOKUP_KEY_TYPE =
ZFIMV_DOA-LOOKUP_KEY_TYPE .
ZFIT_DOA-TCODE =
ZFIMV_DOA-TCODE .
ZFIT_DOA-DOC_TYPE =
ZFIMV_DOA-DOC_TYPE .
ZFIT_DOA-AMOUNT =
ZFIMV_DOA-AMOUNT .
ZFIT_DOA-VORNA =
ZFIMV_DOA-VORNA .
ZFIT_DOA-NACHN =
ZFIMV_DOA-NACHN .
ZFIT_DOA-CHANGEDBY =
ZFIMV_DOA-CHANGEDBY .
ZFIT_DOA-CHANGEDON =
ZFIMV_DOA-CHANGEDON .
    SELECT SINGLE * FROM T000.
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM TSTC WHERE
TCODE = ZFIT_DOA-TCODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TSTCT WHERE
TCODE = TSTC-TCODE AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZFIMV_DOA-TTEXT =
TSTCT-TTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZFIMV_DOA-TTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZFIMV_DOA-TTEXT .
    ENDIF.
ENDFORM.
