*&---------------------------------------------------------------------*
*&  Include           ZFI_UPDATE_SETTLEMENT_TOP
*&---------------------------------------------------------------------*

TABLES:PRPS.
TYPES: BEGIN OF GTY_PRHI,
       POSNR TYPE PS_POSNR,
       PSPHI TYPE PS_PSPHI,
       END OF GTY_PRHI,
       BEGIN OF GTY_JEST,
       OBJNR TYPE J_OBJNR,
       STAT TYPE J_STATUS,
       END OF GTY_JEST,
       BEGIN OF GTY_PRPS,
       PSPNR TYPE PS_POSNR,
       OBJNR TYPE J_OBJNR,
       BELKZ TYPE PS_BELKZ,
       END OF GTY_PRPS,
       BEGIN OF GTY_COBRB,
       OBJNR TYPE J_OBJNR,
       KONTY TYPE KONTY,
       HKONT TYPE SAKNR,
       END OF GTY_COBRB,
       BEGIN OF GTY_COBRB_O,
       OBJNR TYPE J_OBJNR,
       LFDNR TYPE LFDNR,
       PERBZ TYPE PERBZ,
       BETRR type BETRR,
       bwaer type BRGBWAER,
       BREST type AMOUNTREST,
       KONTY TYPE KONTY,
       HKONT TYPE SAKNR,
       ANLN1 TYPE ANLN1,
       END OF GTY_COBRB_O,
       BEGIN OF gty_output,
       pspnr type PS_POSNR,
       hkont type SAKNR,
       anln1 type anln1,
       message type string,
       end OF gty_output.
DATA: GT_PRHI   TYPE TABLE OF GTY_PRHI,
      GS_PRHI   TYPE GTY_PRHI,
      GT_PRPS   TYPE TABLE OF GTY_PRPS,
      GT_INSERT TYPE TABLE OF COBRB,
      GS_UPDATE TYPE COBRB,
      GT_UPDATE TYPE TABLE OF COBRB,
      GS_DELETE TYPE COBRB,
      GT_DELETE TYPE TABLE OF COBRB,
      GS_INSERT TYPE COBRB,
      GS_PRPS   TYPE GTY_PRPS,
      gt_output type TABLE OF gty_output,
      gs_output type gty_output,
      GT_JEST   TYPE TABLE OF GTY_JEST,
      GS_JEST   TYPE GTY_JEST,
      GT_COBRB  TYPE TABLE OF GTY_COBRB,
      GS_COBRB  TYPE GTY_COBRB,
      GT_COBRB_O  TYPE TABLE OF COBRB,"GTY_COBRB_O,
      GT_COBRB_O1  TYPE TABLE OF COBRB, " GTY_COBRB_O,
      gt_COBRB_EX  TYPE TABLE OF COBRB,
      GT_COBRB_O2  TYPE TABLE OF COBRB, "GTY_COBRB_O,
      GT_COBRB_OT  TYPE TABLE OF COBRB,
      GS_COBRB_O  TYPE COBRB, "GTY_COBRB_O,
      GS_COBRB_O1  TYPE COBRB,
      GS_COBRB_OT  TYPE COBRB,
      GS_COBRB_O2  TYPE COBRB. "GTY_COBRB_O.

data: fieldcatalog type slis_t_fieldcat_alv with header line.
data:gv_kostl type kostl.
