FUNCTION Z_TR_CASH_GROUP.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  TABLES
*"      S_ACCT STRUCTURE  ZFAP_BANK_ACC_NO
*"      S_CASH STRUCTURE  ZFTR_CASH_GRP
*"      T_T038 STRUCTURE  ZFTR_T038
*"      T_T012K STRUCTURE  ZFTR_T012K
*"      T_T012K2 STRUCTURE  ZFTR_T012K
*"      T_T001 STRUCTURE  ZFTR_T001
*"      T_T012T STRUCTURE  ZFTR_T012T
*"----------------------------------------------------------------------
  DATA: W_IND TYPE I,
        W_LEN TYPE I,
        W_COUNT TYPE I,
        W_HKONT TYPE N LENGTH 10,
        W_GL(10) TYPE C.

  IF NOT S_CASH[] IS INITIAL.
    SELECT GLIED SELEK BUKRS FROM T038 INTO TABLE T_T038
      WHERE GLIED IN S_CASH AND
            ZEILT = 'G'.

    DELETE T_T038 WHERE SELEK CN  '0123456789+'.

    LOOP AT T_T038.
      CLEAR: W_GL, W_LEN.
      W_IND = SY-TABIX.
      W_LEN = STRLEN( T_T038-SELEK ).
      W_COUNT = 0.
      DO W_LEN TIMES.
        IF T_T038-SELEK+W_COUNT(1) = '+'.
          CONCATENATE W_GL '0' INTO W_GL.
          CONDENSE W_GL NO-GAPS.
        ELSE.
          CONCATENATE W_GL T_T038-SELEK+W_COUNT(1) INTO W_GL.
          CONDENSE W_GL NO-GAPS.
        ENDIF.
        W_COUNT = W_COUNT + 1.
      ENDDO.
      T_T038-SELEK = W_GL.
      MODIFY T_T038 INDEX W_IND TRANSPORTING SELEK.
    ENDLOOP.

    IF NOT T_T038[] IS INITIAL.
      SELECT BUKRS HBKID HKTID BANKN WAERS HKONT FROM T012K INTO TABLE T_T012K
        FOR ALL ENTRIES IN T_T038
        WHERE BANKN IN S_ACCT AND
              HKONT = T_T038-SELEK.

      T_T012K2[] = T_T012K[].
    ENDIF.
  ELSE.
    SELECT BUKRS HBKID HKTID BANKN WAERS HKONT FROM T012K INTO TABLE T_T012K
      WHERE BANKN IN S_ACCT.

    IF SY-SUBRC = 0.
      T_T012K2[] = T_T012K[].
      LOOP AT T_T012K2.
        CLEAR: W_GL, W_LEN.
        W_IND = SY-TABIX.
        W_LEN = STRLEN( T_T012K2-HKONT ).
        W_COUNT = 0.
        DO W_LEN TIMES.
          IF T_T012K2-HKONT+W_COUNT(1) = '0'.
            IF W_GL IS INITIAL OR W_GL CO '+ ' OR W_COUNT = 9.
              CONCATENATE W_GL '+' INTO W_GL.
              CONDENSE W_GL NO-GAPS.
            ELSE.
              CONCATENATE W_GL '0' INTO W_GL.
              CONDENSE W_GL NO-GAPS.
            ENDIF.
          ELSE.
            CONCATENATE W_GL T_T012K2-HKONT+W_COUNT(1) INTO W_GL.
            CONDENSE W_GL NO-GAPS.
          ENDIF.
          W_COUNT = W_COUNT + 1.
        ENDDO.
        IF W_GL+9(1) = '+'.
          T_T012K2-HKONT = W_GL.
        ELSE.
          CLEAR T_T012K2-HKONT.
        ENDIF.
        MODIFY T_T012K2 INDEX W_IND TRANSPORTING HKONT.
      ENDLOOP.
      DELETE T_T012K2 WHERE HKONT IS INITIAL.

      SELECT GLIED SELEK BUKRS FROM T038 INTO TABLE T_T038
        FOR ALL ENTRIES IN T_T012K2
        WHERE ZEILT = 'G' AND
              SELEK = T_T012K2-HKONT AND
              BUKRS = T_T012K2-BUKRS.
    ENDIF.
  ENDIF.

  IF NOT T_T012K[] IS INITIAL.
    SELECT BUKRS BUTXT FROM T001 INTO TABLE T_T001
      FOR ALL ENTRIES IN T_T012K
      WHERE BUKRS = T_T012K-BUKRS.

    SELECT BUKRS HBKID HKTID TEXT1 FROM T012T INTO TABLE T_T012T
      FOR ALL ENTRIES IN T_T012K
      WHERE SPRAS = 'EN' AND
            BUKRS = T_T012K-BUKRS AND
            HBKID = T_T012K-HBKID AND
            HKTID = T_T012K-HKTID.
  ENDIF.



ENDFUNCTION.
