*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFI_MV_SEQN_NUMBTOP.              " Global Data
  INCLUDE LZFI_MV_SEQN_NUMBUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFI_MV_SEQN_NUMBF00                    . " subprograms
  INCLUDE LZFI_MV_SEQN_NUMBI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFI_MV_SEQN_NUMBF...              " Subprograms
* INCLUDE LZFI_MV_SEQN_NUMBO...              " PBO-Modules
* INCLUDE LZFI_MV_SEQN_NUMBI...              " PAI-Modules
