*****           Implementation of object type ZFIBUS1006           *****
INCLUDE <OBJECT>.
BEGIN_DATA OBJECT. " Do not change.. DATA is generated
* only private members may be inserted into structure private
DATA:
" begin of private,
"   to declare private attributes remove comments and
"   insert private attributes here ...
" end of private,
  BEGIN OF KEY,
      BUSINESSPARTNER LIKE BUT000-PARTNER,
  END OF KEY.
END_DATA OBJECT. " Do not change.. DATA is generated


BEGIN_METHOD BPNOTIFICATION CHANGING CONTAINER.
DATA:
      BUSINESSPARTNER TYPE BUT000-PARTNER,
      DECISIONTYPE TYPE ZFIS_TV_WORKFLOW-CONF_TYPE,
      MANAGER TYPE WFSYST-INITIATOR,
      COMMENT TYPE ZFIS_COMMENTS-COMMENTS.

  SWC_GET_ELEMENT CONTAINER 'BusinessPartner' BUSINESSPARTNER.
  SWC_GET_ELEMENT CONTAINER 'DecisionType' DECISIONTYPE.
  SWC_GET_ELEMENT CONTAINER 'Manager' MANAGER.

  CALL FUNCTION 'ZFI_BP_NOTIFICATION'
    EXPORTING
      IMP_BUSINESS_PARTNER = BUSINESSPARTNER
      IMP_DECISION_TYPE = DECISIONTYPE
      IMP_MANAGER = MANAGER
      IMP_COMMENT = COMMENT
    EXCEPTIONS
      OTHERS = 01.
  CASE SY-SUBRC.
    WHEN 0.            " OK
    WHEN OTHERS.       " to be implemented
  ENDCASE.
END_METHOD.

BEGIN_METHOD RELEASEPROCESS CHANGING CONTAINER.
DATA:
      BUSINESSPARTNER TYPE BUT000-PARTNER,
      WORKFLOWID TYPE SWR_STRUCT-WORKITEMID.

  SWC_GET_ELEMENT CONTAINER 'Businesspartner' BUSINESSPARTNER.
  SWC_GET_ELEMENT CONTAINER 'WorkflowId' WORKFLOWID.

  CALL FUNCTION 'ZFI_BP_RELEASE_PROCESS'
    EXPORTING
      IMP_BUSINESSPARTNER = BUSINESSPARTNER
      IMP_WORKFLOW_ID = WORKFLOWID
    EXCEPTIONS
      OTHERS = 01.
  CASE SY-SUBRC.
    WHEN 0.            " OK
    WHEN OTHERS.       " to be implemented
  ENDCASE.
END_METHOD.


BEGIN_METHOD GETNEXTWORKINGDATE CHANGING CONTAINER.

DATA:
      ENDDATE TYPE SYST-DATUM,
      ENDTIME TYPE SYST-UZEIT.

  CALL FUNCTION 'ZFI_GET_NEXT_WORKING_DATE'
    IMPORTING
      EXP_END_DATE = ENDDATE
      EXP_END_TIME = ENDTIME
    EXCEPTIONS
      INVALID_FACTORY_CALENDAR = 9001
      OTHERS = 01.

  CASE SY-SUBRC.
    WHEN 0.            " OK
    WHEN 9001.         " INVALID_FACTORY_CALENDAR
      EXIT_RETURN 9001 sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
    WHEN OTHERS.       " to be implemented
  ENDCASE.

  SWC_SET_ELEMENT CONTAINER 'EndDate' ENDDATE.
  SWC_SET_ELEMENT CONTAINER 'EndTime' ENDTIME.

END_METHOD.

BEGIN_METHOD DUMMY CHANGING CONTAINER.
END_METHOD.



