*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZFIMV_REM_DAYS..................................*
FORM GET_DATA_ZFIMV_REM_DAYS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFIT_REM_DAYS WHERE
(VIM_WHERETAB) .
    CLEAR ZFIMV_REM_DAYS .
ZFIMV_REM_DAYS-MANDT =
ZFIT_REM_DAYS-MANDT .
ZFIMV_REM_DAYS-WF_TYPE =
ZFIT_REM_DAYS-WF_TYPE .
ZFIMV_REM_DAYS-REM_DAYS =
ZFIT_REM_DAYS-REM_DAYS .
<VIM_TOTAL_STRUC> = ZFIMV_REM_DAYS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZFIMV_REM_DAYS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZFIMV_REM_DAYS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZFIMV_REM_DAYS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFIT_REM_DAYS WHERE
  WF_TYPE = ZFIMV_REM_DAYS-WF_TYPE .
    IF SY-SUBRC = 0.
    DELETE ZFIT_REM_DAYS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFIT_REM_DAYS WHERE
  WF_TYPE = ZFIMV_REM_DAYS-WF_TYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFIT_REM_DAYS.
    ENDIF.
ZFIT_REM_DAYS-MANDT =
ZFIMV_REM_DAYS-MANDT .
ZFIT_REM_DAYS-WF_TYPE =
ZFIMV_REM_DAYS-WF_TYPE .
ZFIT_REM_DAYS-REM_DAYS =
ZFIMV_REM_DAYS-REM_DAYS .
    IF SY-SUBRC = 0.
    UPDATE ZFIT_REM_DAYS .
    ELSE.
    INSERT ZFIT_REM_DAYS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZFIMV_REM_DAYS-UPD_FLAG,
STATUS_ZFIMV_REM_DAYS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZFIMV_REM_DAYS.
  SELECT SINGLE * FROM ZFIT_REM_DAYS WHERE
WF_TYPE = ZFIMV_REM_DAYS-WF_TYPE .
ZFIMV_REM_DAYS-MANDT =
ZFIT_REM_DAYS-MANDT .
ZFIMV_REM_DAYS-WF_TYPE =
ZFIT_REM_DAYS-WF_TYPE .
ZFIMV_REM_DAYS-REM_DAYS =
ZFIT_REM_DAYS-REM_DAYS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZFIMV_REM_DAYS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZFIMV_REM_DAYS-WF_TYPE TO
ZFIT_REM_DAYS-WF_TYPE .
MOVE ZFIMV_REM_DAYS-MANDT TO
ZFIT_REM_DAYS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIT_REM_DAYS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIT_REM_DAYS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIT_REM_DAYS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
