REPORT ZFITB001 MESSAGE-ID FR
                LINE-SIZE   132
                NO STANDARD PAGE HEADING.

*====================================================================
TABLES:   RFDT.
TABLES:   T001,  SKA1,  BHDGD,
          T011,  SKAT,
          T011T, SKB1,
          T009,  SKC1A,
          T004,
          T009B.

TABLES:   RFSDO.
TABLES:   TGSB.
TABLES:   FIMSG.
INCLUDE BILAI00_1.                                         "SCRIPT

DATA: GD_FNAME          LIKE FC03TAB-PL00_LFILE,
      GD_PRES           LIKE FCINTAB-FLG_PRES,
      GD_LEAVE_PROGRAM.

DATA: LISTOBJECT LIKE ABAPLIST OCCURS 0 WITH HEADER LINE.
DATA: WRITES LIKE LISTZEILE OCCURS 0 WITH HEADER LINE.
DATA: BEGIN OF RFBILA00_TABLE OCCURS 0,
      RECSIZE(10),
      RECDATA(1000),
      END OF RFBILA00_TABLE.
DATA: PRGNAME    LIKE RSVAR-REPORT.
DATA: BEGIN OF PROGPARMS OCCURS 0.
          INCLUDE STRUCTURE RSPARAMS.
  DATA: END OF PROGPARMS.
*EJECT
BEGIN_OF_SCREEN 1.
  SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT  1(30) TEXT-030.
  SELECTION-SCREEN POSITION       35.
  PARAMETERS:     BILAVERS LIKE T011T-VERSN    MEMORY ID BIL
                                               OBLIGATORY.
  SELECTION-SCREEN COMMENT 40(8) TEXT-031.
  SELECTION-SCREEN POSITION       49.
  PARAMETERS:     BILASPRA LIKE T011-DSPRA     DEFAULT SY-LANGU
                                               OBLIGATORY.
  SELECTION-SCREEN END   OF LINE.
  PARAMETERS:     BILBJAHR LIKE BKPF-GJAHR OBLIGATORY.
  SELECT-OPTIONS: B-MONATE FOR  RFSDO-BILABMON NO-EXTENSION
                                               OBLIGATORY.
  PARAMETERS:     BILVJAHR LIKE BKPF-GJAHR OBLIGATORY.
  SELECT-OPTIONS: V-MONATE FOR  RFSDO-BILAVMON NO-EXTENSION
                                               OBLIGATORY.
  PARAMETERS:     PLANVERS LIKE RFPDO-BILAPVER DEFAULT SPACE,
                  BILANULL LIKE RFPDO-BILANULL DEFAULT SPACE,
                  LOE-VORM LIKE RFPDO-BILALOVM DEFAULT SPACE.
END_OF_SCREEN 1.
BEGIN_OF_SCREEN 2.
  PARAMETERS:
                  BILABKON LIKE RFPDO-BILABKON OBLIGATORY
                                               DEFAULT '1',
                  BILAGKON LIKE RFPDO-BILAGKON OBLIGATORY
                                               DEFAULT '2',
                  BILASUMM LIKE RFPDO-BILASUMM DEFAULT SPACE,
                  BILAVART LIKE RFPDO-BILAVTYP DEFAULT '1',
                  BILASKAL LIKE RFPDO-BILASKAL DEFAULT '0/0',
                  ALLGLSEP LIKE RFPDO-ALLGLSEP  DEFAULT SPACE,
                  MIKFICHE LIKE RFPDO-BILAMIKF  DEFAULT SPACE,
                  ALLGLINE LIKE RFPDO-ALLGLINE DEFAULT SPACE.
PARAMETERS:       BILAPAGE LIKE RFPDO3-BILAPAGNO DEFAULT SPACE.
INCLUDE BILAI00_2.                                       "SCRIPT
END_OF_SCREEN 2.

SELECTION-SCREEN BEGIN OF SCREEN 0030 AS SUBSCREEN.
PARAMETERS:
                  BILABTYP LIKE RFPDO-BILABTYP DEFAULT '1',
                  ALLGALTK LIKE RFPDO1-ALLGALTK DEFAULT SPACE,
                  HOCHRECH LIKE RFPDO-BILAHOCH DEFAULT SPACE,
                  REPWAERS LIKE RFPDO-BILAWAER DEFAULT SPACE,
                  STICHTAG LIKE RFPDO-BILASTID DEFAULT SY-DATUM,
                  KURS_TYP LIKE TCURR-KURST    DEFAULT 'M   ',
                  KALZEITR LIKE RFPDO-BILAKALZ DEFAULT SPACE.
SELECT-OPTIONS:
                  KALZEITB FOR  RFSDO-BILAKALB NO-EXTENSION,
                  KALZEITV FOR  RFSDO-BILAKALV NO-EXTENSION.
PARAMETERS:
                  FI_LC_EX LIKE RFPDO-BILAFILC  DEFAULT SPACE,
                  BILA_EIS LIKE RFPDO-BILA_EIS  DEFAULT SPACE.
PARAMETER:        BILAINFL LIKE J_1ASINFF-COMPPERIOD DEFAULT SPACE.
SELECTION-SCREEN END   OF SCREEN 0030.

* Definition of TabStrips
*BEGIN_OF_TABBED_BLOCK: 1 14.
SELECTION-SCREEN BEGIN OF TABBED BLOCK TABBL1
                                 FOR 14 LINES.
  TABSTRIP: 1 (25).
  SELECTION-SCREEN TAB (25) TAB30
                        USER-COMMAND UCOM30
                        DEFAULT SCREEN 0030.
  TABSTRIP: 2 (25).
SELECTION-SCREEN END   OF BLOCK TABBL1.

SELECTION-SCREEN BEGIN OF SCREEN 2000 AS WINDOW TITLE TEXT-S01.
                                                           "xrp250698
  SELECTION-SCREEN COMMENT /1(80) TEXT-S02.                "xrp250698
  SELECTION-SCREEN COMMENT /1(80) TEXT-S03.                "xrp250698
  SELECTION-SCREEN SKIP.
  SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-F01.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN POSITION 01.
      PARAMETERS  PA_PRES RADIOBUTTON GROUP R01.
      SELECTION-SCREEN COMMENT 03(30) TEXT-S04
                  FOR FIELD PA_PRES.
    SELECTION-SCREEN END OF LINE.                          "xrp250698
    SELECTION-SCREEN BEGIN OF LINE.                        "xrp250698
      SELECTION-SCREEN POSITION 01.                        "xrp250698
      PARAMETERS  PA_APPL RADIOBUTTON GROUP R01.           "xrp250698
      SELECTION-SCREEN COMMENT 03(30) TEXT-S05             "xrp250698
                  FOR FIELD PA_APPL.
    SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 01(30) TEXT-S06
                  FOR FIELD PA_FNAME.
      PARAMETERS  PA_FNAME LIKE FC03TAB-PL00_LFILE OBLIGATORY.
    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK B01.

SELECTION-SCREEN END OF SCREEN 2000.

*BILA&I00 replaced by BILAI00_1 and BILAI00_2
*INCLUDE BILA&I00.                      "SCRIPT

*EJECT
*--------------------------------------------------------------------*
*        INITIALIZATION                                              *
*--------------------------------------------------------------------*
INITIALIZATION.
  GET_TABSTRIP_TITLE: 1,2.
  TAB30 = TEXT-051.
* Vorschlagswerte Berichts- und Vergleichsjahr
* --------------------------------------------

*======================================================================

PRGNAME = SY-REPID.
*CALL FUNCTION 'RS_LIST_SELECTION_TABLE'
*     EXPORTING REPORT = PRGNAME
*              SELTEXT = 'X'
*          TABLES
*              SEL_TAB = PROGPARMS.



START-OF-SELECTION.
CALL FUNCTION 'RS_REFRESH_FROM_SELECTOPTIONS'
       EXPORTING
            CURR_REPORT     = PRGNAME
       TABLES
            SELECTION_TABLE = PROGPARMS
       EXCEPTIONS
            NOT_FOUND       = 1
            NO_REPORT       = 2
            OTHERS          = 3.


  SUBMIT RFBILA00 EXPORTING LIST TO MEMORY AND RETURN
         WITH SELECTION-TABLE PROGPARMS.

  CALL FUNCTION 'LIST_FROM_MEMORY'
       TABLES
            LISTOBJECT = LISTOBJECT
       EXCEPTIONS
            EMPTY_LIST = 1
            OTHERS     = 2.

       CALL FUNCTION 'LIST_TO_ASCI'
               TABLES
                    LISTOBJECT = LISTOBJECT
                    LISTASCI   = WRITES.


        CALL FUNCTION 'WRITE_LIST'
             TABLES
                  LISTOBJECT = LISTOBJECT
             EXCEPTIONS
                  EMPTY_LIST = 1
                  OTHERS     = 2.

        CALL FUNCTION 'LIST_FREE_MEMORY'
             TABLES
                  LISTOBJECT = LISTOBJECT
             EXCEPTIONS
                  OTHERS     = 1.


*  IF SY-SUBRC <> 0.
*     WRITE: /11 'IT'S NOT OK ' SY-SUBRC.
*  ELSE.
*     LOOP AT LISTOBJECT.
*          WRITE: /1 132 LISTOBJECT.
*     ENDLOOP.
*  ENDIF.
  STOP.



