*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFIT_VALID_BLARTTOP.              " Global Data
  INCLUDE LZFIT_VALID_BLARTUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFIT_VALID_BLARTF00                    . " subprograms
  INCLUDE LZFIT_VALID_BLARTI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFIT_VALID_BLARTF...              " Subprograms
* INCLUDE LZFIT_VALID_BLARTO...              " PBO-Modules
* INCLUDE LZFIT_VALID_BLARTI...              " PAI-Modules
