"Name: \FU:PTRA_WEB_EXPENSE_FORM_DATA_GET\SE:END\EI
ENHANCEMENT 0 ZFITVE_EXPENSE_FORM.
*
  DATA:wa_totals TYPE ptrv_web_totals.
DATA:IT_TOTALS TYPE  PTRV_WEB_TOTALS_T.

DATA:WA_ET_RECEIPTS_TAX_FREE_TOTALS TYPE PTRV_WEB_RECEIPTS_FORM_TLS.
DATA:IT_ET_RECEIPTS_TAX_FREE_TOTALS TYPE PTRV_WEB_RECEIPTS_FORM_TLS_T.

DATA:WA_ET_RECEIPTS_TAXABLE_TOTALS TYPE PTRV_WEB_RECEIPTS_FORM_TLS.
DATA:IT_ET_RECEIPTS_TAXABLE_TOTALS TYPE PTRV_WEB_RECEIPTS_FORM_TLS_T.

DATA:WA_ET_RECEIPTS_TAX_FREE TYPE PTRV_WEB_RECEIPTS_FORM.
DATA:IT_ET_RECEIPTS_TAX_FREE TYPE PTRV_WEB_RECEIPTS_FORM_T.

DATA:WA_ET_RECEIPTS_TAXABLE TYPE PTRV_WEB_RECEIPTS_FORM.
DATA:IT_ET_RECEIPTS_TAXABLE TYPE PTRV_WEB_RECEIPTS_FORM_T.

break sahmad.
*For Details Section of Adobe Form which removes Paid by Company text
IF NOT et_totals is initial.
    LOOP AT et_totals INTO wa_totals.
      SEARCH wa_totals-line_type_name FOR 'Paid by Company'.
      IF sy-subrc EQ 0.
        REPLACE ALL OCCURRENCES OF 'Paid by Company'
                  IN wa_totals-line_type_name WITH ' '.
      ENDIF.
      APPEND wa_totals TO IT_TOTALS.
      CLEAR wa_totals.
    ENDLOOP.
    REFRESH: et_totals.
    et_totals[] = IT_TOTALS[].
    REFRESH: IT_TOTALS.
Endif.
*For Report Summary of Adobe Form which removes Paid by Company text
*Tax Free total receipts
IF NOT ET_RECEIPTS_TAX_FREE_TOTALS is initial.
    LOOP at ET_RECEIPTS_TAX_FREE_TOTALS into WA_ET_RECEIPTS_TAX_FREE_TOTALS.
      SEARCH WA_ET_RECEIPTS_TAX_FREE_TOTALS-EXP_TYPE_NAME FOR 'Paid by Company'.
      IF sy-subrc EQ 0.
          REPLACE ALL OCCURRENCES OF 'Paid by Company' IN
               WA_ET_RECEIPTS_TAX_FREE_TOTALS-EXP_TYPE_NAME WITH ' '.
      ENDIF.
      APPEND WA_ET_RECEIPTS_TAX_FREE_TOTALS to IT_ET_RECEIPTS_TAX_FREE_TOTALS.
      CLEAR WA_ET_RECEIPTS_TAX_FREE_TOTALS.
    ENDLOOP.
    REFRESH: ET_RECEIPTS_TAX_FREE_TOTALS.
    ET_RECEIPTS_TAX_FREE_TOTALS[] = IT_ET_RECEIPTS_TAX_FREE_TOTALS[].
    REFRESH IT_ET_RECEIPTS_TAX_FREE_TOTALS.
Endif.
*Taxable total receipts.
IF NOT ET_RECEIPTS_TAXABLE_TOTALS is initial.
    LOOP at ET_RECEIPTS_TAXABLE_TOTALS into WA_ET_RECEIPTS_TAXABLE_TOTALS.
         SEARCH WA_ET_RECEIPTS_TAXABLE_TOTALS-EXP_TYPE_NAME
                                     FOR 'Paid by Company'.
         IF sy-subrc EQ 0.
           REPLACE ALL OCCURRENCES OF 'Paid by Company' IN
                   WA_ET_RECEIPTS_TAXABLE_TOTALS-EXP_TYPE_NAME WITH ' '.
         ENDIF.
         APPEND WA_ET_RECEIPTS_TAXABLE_TOTALS to IT_ET_RECEIPTS_TAXABLE_TOTALS.
         CLEAR WA_ET_RECEIPTS_TAXABLE_TOTALS.
   ENDLOOP.
   REFRESH: ET_RECEIPTS_TAXABLE_TOTALS.
   ET_RECEIPTS_TAXABLE_TOTALS[] = IT_ET_RECEIPTS_TAXABLE_TOTALS[].
   REFRESH IT_ET_RECEIPTS_TAXABLE_TOTALS.
Endif.
*Tax free receipts
IF NOT ET_RECEIPTS_TAX_FREE is initial.
    LOOP at ET_RECEIPTS_TAX_FREE into WA_ET_RECEIPTS_TAX_FREE.
        SEARCH WA_ET_RECEIPTS_TAX_FREE-EXP_TYPE_NAME
                                  FOR 'Paid by Company'.
        IF sy-subrc EQ 0.
            REPLACE ALL OCCURRENCES OF 'Paid by Company' IN
                    WA_ET_RECEIPTS_TAX_FREE-EXP_TYPE_NAME WITH ' '.
        ENDIF.
        APPEND WA_ET_RECEIPTS_TAX_FREE to IT_ET_RECEIPTS_TAX_FREE.
        CLEAR WA_ET_RECEIPTS_TAX_FREE.
    ENDLOOP.
    REFRESH: ET_RECEIPTS_TAX_FREE.
    ET_RECEIPTS_TAX_FREE[] = IT_ET_RECEIPTS_TAX_FREE[].
    REFRESH IT_ET_RECEIPTS_TAX_FREE.
Endif.
*Taxable receipts
IF NOT ET_RECEIPTS_TAXABLE is initial.
    LOOP at ET_RECEIPTS_TAXABLE into WA_ET_RECEIPTS_TAXABLE.
         SEARCH WA_ET_RECEIPTS_TAXABLE-EXP_TYPE_NAME
                             FOR 'Paid by Company'.
         IF sy-subrc EQ 0.
            REPLACE ALL OCCURRENCES OF 'Paid by Company' IN
                 WA_ET_RECEIPTS_TAXABLE-EXP_TYPE_NAME WITH ' '.
         ENDIF.
         APPEND WA_ET_RECEIPTS_TAXABLE to IT_ET_RECEIPTS_TAXABLE.
         CLEAR WA_ET_RECEIPTS_TAXABLE.
    ENDLOOP.
    REFRESH: ET_RECEIPTS_TAXABLE.
    ET_RECEIPTS_TAXABLE[] = IT_ET_RECEIPTS_TAXABLE[].
    REFRESH IT_ET_RECEIPTS_TAXABLE.
Endif.
ENDENHANCEMENT.
