*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFIT_FCALENDARTOP.                " Global Data
  INCLUDE LZFIT_FCALENDARUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFIT_FCALENDARF00                      . " subprograms
  INCLUDE LZFIT_FCALENDARI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFIT_FCALENDARF...                " Subprograms
* INCLUDE LZFIT_FCALENDARO...                " PBO-Modules
* INCLUDE LZFIT_FCALENDARI...                " PAI-Modules
