*&---------------------------------------------------------------------*
*&  Include           ZHR_DOA_DEMO_OUT_SCRN
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS : S_tcode FOR ZFIMV_DOA_NEW-TCODE NO INTERVALS.
SELECT-OPTIONS : S_type  FOR ZFIMV_DOA_NEW-DOC_TYPE NO INTERVALS.
SELECT-OPTIONS : S_EEGrp FOR pa0001-persg NO INTERVALS .
SELECTION-SCREEN END OF BLOCK B1.


SELECTION-SCREEN BEGIN OF BLOCK s3 WITH FRAME TITLE text-t03.

SELECTION-SCREEN: BEGIN OF LINE,
POSITION 1, COMMENT 1(20) text-c09 FOR FIELD p_test.
PARAMETERS:p_test RADIOBUTTON GROUP r2 DEFAULT 'X' USER-COMMAND upd1.
SELECTION-SCREEN:POSITION 40,COMMENT 40(20) text-c10 FOR FIELD p_prd.
PARAMETERS:p_prd RADIOBUTTON GROUP r2.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK s3.

SELECTION-SCREEN BEGIN OF BLOCK s1 WITH FRAME TITLE text-t01.

SELECTION-SCREEN: BEGIN OF LINE,
POSITION 1,COMMENT 1(20) text-c11 FOR FIELD p_pres MODIF ID p1.
PARAMETERS:p_pres RADIOBUTTON GROUP r1 DEFAULT 'X' USER-COMMAND upd
MODIF ID p1.
SELECTION-SCREEN:POSITION 40,COMMENT 40(20) text-c12 FOR FIELD p_appl
MODIF ID p1.
PARAMETERS:p_appl RADIOBUTTON GROUP r1 MODIF ID p1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK s1.

SELECTION-SCREEN BEGIN OF BLOCK s2 WITH FRAME TITLE text-t02.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(11) text-p02 FOR FIELD p_file1 MODIF ID m1.
PARAMETERS:p_path1 TYPE string MODIF ID m1.
PARAMETERS:p_file1 TYPE string MODIF ID m1.
SELECTION-SCREEN : END OF LINE.

SELECTION-SCREEN :BEGIN OF LINE .
SELECTION-SCREEN COMMENT 1(11) text-p03 FOR FIELD p_file3 MODIF ID m1.
PARAMETERS : p_path3 TYPE string MODIF ID m1.
PARAMETERS : p_file3 TYPE string MODIF ID m1.
SELECTION-SCREEN : END OF LINE.

SELECTION-SCREEN END OF BLOCK s2.

SELECTION-SCREEN BEGIN OF BLOCK s4 WITH FRAME TITLE text-t04.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(11) text-p02 FOR FIELD p_file2 MODIF ID m2.
PARAMETERS:p_path2 TYPE string MODIF ID m2.
PARAMETERS:p_file2 TYPE string MODIF ID m2.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN :BEGIN OF LINE .
SELECTION-SCREEN COMMENT 1(11) text-p03 FOR FIELD p_file4 MODIF ID m2.
PARAMETERS : p_path4 TYPE string MODIF ID m2.
PARAMETERS : p_file4 TYPE string MODIF ID m2.
SELECTION-SCREEN : END OF LINE.

SELECTION-SCREEN END OF BLOCK s4.
AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    IF screen-group1 = 'M2'.
      IF p_pres = space .
        screen-active = 1.
      ELSE.
        screen-active = 0.
      ENDIF.
      MODIFY SCREEN.
    ENDIF.

    IF screen-group1 = 'M1'.
      IF p_appl = space .
        screen-active = 1.
      ELSE.
        screen-active = 0.
      ENDIF.
      MODIFY SCREEN.
    ENDIF.

    IF p_test = gc_x.
      IF  screen-group1 = 'M1'
         OR screen-group1 = 'M2'
         OR screen-group1 = 'M3'.
        screen-active = 0.
        MODIFY SCREEN.
      ENDIF.
    ENDIF.
  ENDLOOP.
  PERFORM default_filename.
