*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 12/30/1997 at 15:35:09 by user SAPDEVE
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZVGRTOP.      " Global Data
  INCLUDE LZVGRUXX.      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZVGRF00.      " subprograms
  INCLUDE LZVGRI00.      " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX.      " subprograms
  INCLUDE LSVIMOXX.      " PBO modules
  INCLUDE LSVIMIXX.      " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZVGRF...      " Subprograms
* INCLUDE LZVGRO...      " PBO-Modules
* INCLUDE LZVGRI...      " PAI-Modules
